# Generated by Django 4.2.3 on 2023-07-05 13:43

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('Femal', 'Female'), ('Male', 'Male')], max_length=64)),
                ('age', models.IntegerField()),
                ('position', models.CharField(choices=[('Developer', 'Developer'), ('Designer', 'Designer'), ('Assistant', 'Assistant')], max_length=64)),
                ('language', multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('Mandarin', 'Mandarin'), ('Japanese', 'Japanese'), ('Korean', 'Korean')], max_length=64)),
                ('salary', models.IntegerField()),
                ('_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '人員列表',
                'verbose_name_plural': '人員列表',
                'ordering': ['-_time'],
            },
        ),
    ]
